"""Add ads tables

Revision ID: 386ec6b86e6a
Revises: 6f9ef3069a2c
Create Date: 2026-05-05 17:10:14.379363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386ec6b86e6a'
down_revision: Union[str, None] = '6f9ef3069a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
