"""add recently viewed ads

Revision ID: 6f9ef3069a2c
Revises: 856029114468
Create Date: 2026-05-04 11:22:44.740121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9ef3069a2c'
down_revision: Union[str, None] = '856029114468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recently_viewed_ads',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ad_id', name='uq_user_ad_recently_viewed')
    )
    op.create_index(op.f('ix_recently_viewed_ads_id'), 'recently_viewed_ads', ['id'], unique=False)
    op.create_index(op.f('ix_recently_viewed_ads_uuid'), 'recently_viewed_ads', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recently_viewed_ads_uuid'), table_name='recently_viewed_ads')
    op.drop_index(op.f('ix_recently_viewed_ads_id'), table_name='recently_viewed_ads')
    op.drop_table('recently_viewed_ads')
    # ### end Alembic commands ###
