"""add favorites table

Revision ID: 8f4ebcab92d2
Revises: 9c6ca0ff8aa8
Create Date: 2026-04-28 17:12:37.688506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4ebcab92d2'
down_revision: Union[str, None] = '9c6ca0ff8aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
